<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../styles.css">
    <title>Промисы, async/await</title>
</head>
<body>
    <div class="learn-page__layout">
        <h1><a href="../../1_module/">Back to module 1</a></h1>
        <section class="learn-page__layout--study-block">
            <h3>Обозначения:</h3>
            <div class="text checked">Зеленый блок = прогресс изучения; Зеленая рамка = повторил, классно.</div>
            <div class="help helpful">Синий блок = полезная подсказка; Синяя рамка = очень важно, очень классно.</div>
            <div class="script useless">Красный блок = задача; Красная рамка = на мой взгляд не стоит внимания.</div>
        </section>
        <section class="learn-page__layout--study-block helpful">
            <h3>11.1 Введение: колбэки</h3>
            <div class="text">
                <b>Основы</b>
                <p>
                    Многие действия в JavaScript асинхронные. Пример: loadScript('/my/script.js'); // загрузка скрипта будет завершена не сейчас, а потом.<br><br>
                    Если после вызова loadScript(…) есть какой-то код, то он не будет ждать, пока скрипт загрузится.<br><br>
                    Если попробуем вызвать функцию после loadScript(…), то получим ошибку. // такой функции не существует! <br><br>
                    Для этого и нужны колбэки. Передадим функцию callback вторым аргументом в loadScript, чтобы вызвать её, когда скрипт загрузится:
                </p>
                <img src="./img/1.png" alt="" width="100%">
                <p>
                    Теперь, если мы хотим вызвать функцию из скрипта, нужно делать это в колбэке: <br><br>
                    loadScript('/my/script.js', function() {newFunction(); // теперь всё работает}); <br><br>
                    <b>Смысл такой: вторым аргументом передаётся функция (обычно анонимная), которая выполняется по завершении действия.</b>
                </p>
            </div>
            <div class="help">
                <b>Перехват ошибок</b>
                <p>
                    А что если загрузить скрипт не удалось? Колбэк должен уметь реагировать на возможные проблемы.<br><br>
                    Мы вызываем callback(null, script) в случае успешной загрузки и callback(error), если загрузить скрипт не удалось.
                </p>
                <img src="./img/2.png" alt="" width="100%">
                <p>
                    Пример: loadScript('/my/script.js', function(error, script) {if (error) {// обрабатываем ошибку} else {// скрипт успешно загружен}});
                </p>
            </div>
            <div class="help">
                <b>Колбэк в колбэке (адская пирамида вызовов)</b>
                <p>
                    Как нам загрузить два скрипта один за другим: сначала первый, а за ним второй?<br><br>
                    Первое, что приходит в голову, вызвать loadScript ещё раз уже внутри колбэка. <br></br>
                    Но таких вызовов может быть бесконечность. Это называют «адом колбэков».<br><br>
                    Мы можем попытаться решить эту проблему, изолируя каждое действие в отдельную функцию (то же, но без вложенности).
                </p>
            </div>
            <div class="script">
                <b>Задачи. Анимация круга с помощью колбэка</b>
                <p>
                    <code>
                        .circle {
                            transition-property: width, height, margin-left, margin-top;
                            transition-duration: 2s;
                            position: fixed;
                            transform: translateX(-50%) translateY(-50%);
                            background-color: red;
                            border-radius: 50%;
                        }
                        .message {
                            font-size: 16px;
                            line-height: 200px;
                            text-align: center;
                        }
                    </code>
                </p>
                <p>
                    <code>
                        function go() {
                            showCircle(150, 150, 100, div => {
                            div.classList.add('message-ball');
                            div.append("Hello, world!");
                            });
                        }
                        function showCircle(cx, cy, radius, callback) {
                            let div = document.createElement('div');
                            div.style.width = 0;
                            div.style.height = 0;
                            div.style.left = cx + 'px';
                            div.style.top = cy + 'px';
                            div.className = 'circle';
                            document.body.append(div);
                        
                            setTimeout(() => {
                                div.style.width = radius * 2 + 'px';
                                div.style.height = radius * 2 + 'px';
                        
                                div.addEventListener('transitionend', function handler() {
                                    div.removeEventListener('transitionend', handler);
                                    callback(div);
                                });
                            });
                        }
                    </code>
                </p>
            </div>
        </section>
        <section class="learn-page__layout--study-block helpful">
            <h3>11.2 Промисы</h3>
            <div class="text">
                <b>Основы</b>
                <p>
                    Синтаксис создания Promise: let promise = new Promise(function(resolve, reject) {// функция-исполнитель (executor)});<br><br>
                    Функция, переданная в конструкцию new Promise, называется исполнитель (executor). Когда Promise создаётся, 
                    она запускается автоматически. Она должна содержать «создающий» код, который когда-нибудь создаст результат. <br><br>
                    resolve и reject – это колбэки, которые предоставляет сам JavaScript. Наш код – только внутри исполнителя. <br><br>
                    Когда он получает результат, сейчас или позже – не важно, он должен вызвать один из этих колбэков: <br><br>
                    1) resolve(value) — если работа завершилась успешно, с результатом value. <br><br>
                    2) reject(error) — если произошла ошибка, error – объект ошибки. <br><br><br>
                    У объекта promise, возвращаемого конструктором new Promise, есть внутренние свойства: <br><br>
                    1) state («состояние») — вначале "pending" («ожидание»), потом меняется на "fulfilled" 
                    («выполнено успешно») при вызове resolve или на "rejected" («выполнено с ошибкой») при вызове reject. <br><br>
                    2) result («результат») — вначале undefined, далее изменяется на value при вызове resolve(value) или на error при вызове reject(error). <br><br>
                    Так что исполнитель по итогу переводит promise в одно из двух состояний:
                </p>
                <img src="./img/3.png" alt="" width="100%">
            </div>
            <div class="help">
                <b>Может быть что-то одно: либо результат, либо ошибка</b>
                <p>
                    Исполнитель должен вызвать что-то одно: resolve или reject. Состояние промиса может быть изменено только один раз. <br><br>
                    Все последующие вызовы resolve и reject будут проигнорированы.
                </p>
                <img src="./img/3.png" alt="" width="100%">
            </div>
            <div class="help">
                <b>Потребители: then, catch, finally</b>
                <p>
                    1) then: promise.then(function(result) { /* обработает успешное выполнение */ },function(error) { /* обработает ошибку */ }); <br><br>
                    Первый аргумент метода .then – функция, которая выполняется, когда промис переходит в состояние «выполнен успешно», и получает результат. <br><br>
                    Второй аргумент .then – функция, которая выполняется, когда промис переходит в состояние «выполнен с ошибкой», и получает ошибку. <br><br>
                    Пример: promise.then(result => alert(result), // выведет "done!" через одну секундуerror => alert(error) // не будет запущена); <br><br><br>
                    2) catch: Если мы хотели бы только обработать ошибку, то можно использовать null в качестве первого аргумента: .then(null, errorHandlingFunction). 
                    Или можно воспользоваться методом .catch(errorHandlingFunction), который сделает тоже самое: <br><br>
                    Вызов .catch(f) – это сокращённый, «укороченный» вариант .then(null, f). <br><br><br>
                    3) finally: Вызов .finally(f) похож на .then(f, f), в том смысле, что f выполнится в любом случае, когда промис завершится: успешно или с ошибкой. <br><br>
                    finally хорошо подходит для очистки, например остановки индикатора загрузки, его ведь нужно остановить вне зависимости от результата.
                </p>
                <img src="./img/3.png" alt="" width="100%">
            </div>
            <div class="text">
                <b>Пример: loadScript</b>
                <p>
                    Вариант с колбэками:
                </p>
                <img src="./img/4.png" alt="" width="100%">
                <p>
                    Вариант с промисами:
                </p>
                <img src="./img/5.png" alt="" width="100%">
            </div>
            <div class="script">
                <b>Задачи. Можно ли "перевыполнить" промис?</b>
                <p>
                    <code>
                        1
                    </code>
                </p>
            </div>
            <div class="script">
                <b>Задачи. Задержка на промисах</b>
                <p>
                    <code>
                        function delay(ms) {
                            return new Promise(resolve => setTimeout(resolve, ms)); // resolve = callback
                        }
                    </code>
                </p>
            </div>
        </section>
        <section class="learn-page__layout--study-block helpful">
            <h3>11.3 Цепочка промисов</h3>
            <div class="text">
                <b>Основы</b>
                <p>
                    Результат первого промиса передаётся по цепочке обработчиков .then<br><br>
                    1) Начальный промис успешно выполняется через 1 секунду (*)<br><br>
                    2) Затем вызывается обработчик в .then (**). <br><br>
                    3) Возвращаемое им значение передаётся дальше в следующий обработчик .then (***) <br><br>
                    4) …и так далее. <br><br><br>
                    Если обработчик в .then (или в catch/finally, без разницы) возвращает промис, последующие элементы цепочки ждут, 
                    пока этот промис выполнится. Когда это происходит, результат его выполнения (или ошибка) передаётся дальше.
                </p>
                <img src="./img/6.png" alt="" width="100%">
            </div>
            <div class="script">
                <b>Задачи. Промисы: сравните then и catch</b>
                <p>
                    <code>
                        Нет. Во втором пример ошибка останется необработанной.
                    </code>
                </p>
            </div>
        </section>
        <section class="learn-page__layout--study-block helpful">
            <h3>11.4 Промисы: обработка ошибок</h3>
            <div class="text">
                <b>Основы</b>
                <p>
                    Цепочки промисов отлично подходят для перехвата ошибок. Если промис завершается с ошибкой, 
                    то управление переходит в ближайший обработчик ошибок. Пример<br><br>
                    fetch('https://no-such-server.blabla').then(response => response.json()).catch(err => alert(err)) // TypeError: failed to fetch
                </p>
            </div>
            <div class="help">
                <b>Неявный try…catch</b>
                <p>
                    .catch перехватывает все виды ошибок в промисах: будь то вызов reject() или ошибка, брошенная в обработчике при помощи throw. <br><br>
                    Поэтому обрабатываются все синхронные ошибки. Если ошибка генерируется не по ходу выполнения кода, а позже. Поэтому промис не может обработать её. <br></br>
                    Например, если ошибка находится в setTimeout.
                </p>
            </div>
            <div class="help">
                <b>Пробрасывание ошибок</b>
                <p>
                    Необходимо размещать .catch там, где мы хотим обработать ошибки и знаем, как это сделать. Обработчик может проанализировать 
                    ошибку (могут быть полезны пользовательские классы ошибок) и пробросить её, если ничего не знает о ней (возможно, это программная ошибка).
                </p>
            </div>
            <div class="help">
                <b>Необработанные ошибки</b>
                <p>
                    Что произойдёт, если ошибка не будет обработана? Например, мы просто забыли добавить .catch. <br><br>
                    JavaScript-движок отслеживает такие ситуации и генерирует в этом случае глобальную ошибку. <br><br>
                    В браузере мы можем поймать такие ошибки, используя событие unhandledrejection: <br><br>
                    // объект события имеет два специальных свойства: promise (промис, который сгенерировал ошибку), reason (объект ошибки, которая не была обработана) <br><br>
                    window.addEventListener('unhandledrejection', function(event) {alert(event.promise);alert(event.reason);});
                </p>
            </div>
            <div class="script">
                <b>Задачи. Ошибка в setTimeout</b>
                <p>
                    <code>
                        Нет.
                    </code>
                </p>
            </div>
        </section>
        <section class="learn-page__layout--study-block helpful">
            <h3>11.5 Promise API</h3>
            <div class="text">
                <b>Основы</b>
                <p>
                    В классе Promise есть 5 статических методов.<br><br>
                    1) Promise.all(promises) – ожидает выполнения всех промисов и возвращает массив с результатами. <br><br>
                    Если любой из указанных промисов вернёт ошибку, то результатом работы Promise.all будет эта ошибка, результаты остальных промисов будут игнорироваться. <br><br>
                    2) Promise.allSettled(promises) (добавлен недавно) – ждёт, пока все промисы завершатся и возвращает их результаты в виде массива с объектами, у каждого объекта два свойства: <br><br>
                    state: "fulfilled", если выполнен успешно или "rejected", если ошибка, <br><br>
                    value – результат, если успешно или reason – ошибка, если нет. <br><br>
                    3) Promise.race(promises) – ожидает первый выполненный промис, который становится его результатом, остальные игнорируются. <br><br>
                    4) Promise.resolve(value) – возвращает успешно выполнившийся промис с результатом value. <br><br>
                    5) Promise.reject(error) – возвращает промис с ошибкой error. <br><br>
                    Из всех перечисленных методов, самый часто используемый – это, пожалуй, Promise.all.
                </p>
            </div>
        </section>
        <section class="learn-page__layout--study-block helpful">
            <h3>11.6 Промисификация</h3>
            <div class="text">
                <b>Основы</b>
                <p>
                    Мы берём функцию, которая принимает колбэк и меняем её, чтобы она вместо этого возвращала промис.<br><br>
                    Такие преобразования часто необходимы в реальной жизни, так как многие функции и библиотеки основаны на колбэках, 
                    а использование промисов более удобно, поэтому есть смысл «промисифицировать» их. <br><br>
                    Например, у нас есть loadScript(src, callback):
                </p>
                <img src="./img/7.png" alt="" width="100%">
                <p>Из неё сделаем это:</p>
                <img src="./img/8.png" alt="" width="100%">
            </div>
            <div class="help">
                <b>На заметку</b>
                <p>
                    Промисификация – это отличный подход, особенно, если вы будете использовать async/await, но она не является тотальной заменой любых колбэков. <br><br>
                    Помните, промис может иметь только один результат, но колбэк технически может вызываться сколько угодно раз. <br><br>
                    Поэтому промисификация используется для функций, которые вызывают колбэк только один раз. Последующие вызовы колбэка будут проигнорированы.
                </p>
            </div>
        </section>
        <section class="learn-page__layout--study-block helpful">
            <h3>11.7 Микрозадачи</h3>
            <div class="text">
                <b>Очередь микрозадач</b>
                <p>
                    Асинхронные задачи требуют правильного управления. Для этого стандарт предусматривает внутреннюю очередь PromiseJobs, 
                    более известную как «очередь микрозадач (microtask queue)»<br><br>
                    Когда промис выполнен, его обработчики .then/catch/finally попадают в очередь. Они пока не выполняются. <br><br>
                    Движок JavaScript берёт задачу из очереди и выполняет её, когда он освободится от выполнения текущего кода.
                </p>
                <img src="./img/9.png" alt="" width="100%">
                <p>
                    Что делать если порядок имеет значение для нас? Использовать .then: <br><br>
                    Promise.resolve().then(() => alert("промис выполнен!")).then(() => alert("код выполнен")); <br><br>
                    Обработчики .then/catch/finally вызываются после выполнения текущего кода. <br><br>
                    Если нам нужно гарантировать выполнение какого-то кода после .then/catch/finally, 
                    то лучше всего добавить его вызов в цепочку .then.
                </p>
            </div>
            <div class="text">
                <b>Необработанные ошибки</b>
                <p>
                    "Необработанная ошибка" возникает в случае, если ошибка промиса не обрабатывается в конце очереди микрозадач.<br><br>
                    Поэтому стоит добавлять .catch() для обработки ошибок.
                </p>
            </div>
        </section>
        <section class="learn-page__layout--study-block helpful">
            <h3>11.8 Async/await</h3>
            <div class="text">
                <b>Асинхронные функции</b>
                <p>
                    Существует специальный синтаксис для работы с промисами, который называется «async/await». <br><br>
                    1) async ставится перед функцией, вот так: async function f() {return 1;} <br><br>
                    async функция всегда возвращает промис. <br><br>
                    2) await работает только внутри async–функций. let value = await promise; <br><br>
                    await заставит интерпретатор JavaScript ждать до тех пор, пока промис справа от await не выполнится. 
                    После чего оно вернёт его результат, и выполнение кода продолжится. <br><br>
                    <b>По сути, это просто «синтаксический сахар» для получения результата промиса, более наглядный, чем promise.then.</b> <br><br>
                    Пример работы с async/await:
                </p>
                <img src="./img/10.png" alt="" width="100%">
            </div>
            <div class="help">
                <b>Асинхронные методы классов</b>
                <p>
                    Для объявления асинхронного метода достаточно написать async перед именем: <br><br>
                    class Waiter {async wait() {return await Promise.resolve(1);}} <br><br>
                    new Waiter().wait().then(alert); // 1
                </p>
            </div>
            <div class="text">
                <b>Обработка ошибок</b>
                <p>
                    На практике промис может завершиться с ошибкой не сразу, а через некоторое время. В этом случае будет задержка, а затем await выбросит исключение.<br><br>
                    Такие ошибки можно ловить, используя try..catch. В случае ошибки выполнение try прерывается и управление прыгает в начало блока catch:
                </p>
                <img src="./img/11.png" alt="" width="100%">
            </div>
            <div class="script">
                <b>Задачи. Перепишите, используя async/await</b>
                <p>
                    <code>
                        const loadJson = async (url) => {
                            let response = await fetch(url);
                            if (response.status == 200) {
                                let json = await response.json();
                                return json;
                            }
                            throw new Error(response.status);
                        }
                    </code>
                </p>
            </div>
        </section>
    </div>
</body>
</html>